import { readFileSync } from 'node:fs';
import { builtinModules } from 'node:module';
import { defineConfig } from 'vite';
import dts from 'vite-plugin-dts';

const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8')) as {
  dependencies?: Record<string, string>;
  peerDependencies?: Record<string, string>;
};

const banner = `/*! THIS IS A GENERATED/BUNDLED FILE BY VITE + ROLLDOWN — see the repository for source. */`;

// Externalize every runtime and peer dependency so consumers' bundlers can
// tree-shake them. This library targets Obsidian plugin bundles, so the
// library itself stays small and the consumer decides what ships in main.js.
const runtimeDeps = [
  ...Object.keys(pkg.dependencies ?? {}),
  ...Object.keys(pkg.peerDependencies ?? {}),
];

export default defineConfig(({ mode }) => {
  const isProd = mode === 'production';

  return {
    plugins: [
      dts({
        include: ['src'],
        rollupTypes: true,
        tsconfigPath: './tsconfig.json',
      }),
    ],
    build: {
      lib: {
        entry: 'src/index.ts',
        formats: ['es'],
        fileName: () => 'index.js',
      },
      rollupOptions: {
        external: [
          ...runtimeDeps,
          ...runtimeDeps.map(
            (dep) => new RegExp(`^${dep.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&')}/`),
          ),
          ...builtinModules,
          ...builtinModules.map((m) => `node:${m}`),
        ],
        output: {
          banner,
        },
      },
      target: 'es2022',
      sourcemap: true,
      minify: isProd,
      outDir: 'dist',
      emptyOutDir: true,
    },
  };
});
